export const ACTION_TYPES = {
    INCREASE_APPLE_QUANTITY: "INCREASE_APPLE_QUANTITY",
    DECREASE_APPLE_QUANTITY: "DECREASE_APPLE_QUANTITY",
    INCREASE_GRAPES_QUANTITY: "INCREASE_GRAPES_QUANTITY",
    DECREASE_GRAPES_QUANTITY: "DECREASE_GRAPES_QUANTITY",
    INCREASE_PEACHES_QUANTITY: "INCREASE_PEACHES_QUANTITY",
    DECREASE_PEACHES_QUANTITY: "DECREASE_PEACHES_QUANTITY"
}